#!/bin/sh
branch_name=$(git rev-parse --abbrev-ref HEAD)

if echo "$branch_name" | grep -q '[^a-zA-Z0-9/_\-:]'; then
    echo "X [Husky] Push blocked: the branch name '$branch_name' contains forbidden characters."
    echo "=> Use only unaccented letters, numbers, '/', '_', ':', and '-'."
    exit 1
fi